default:
  stock: &stock
    - name: total_stock
      type: stock
      symbol: "VTI"
    - name: total_bond
      type: stock
      symbol: "BND"
  all:
    - *stock

  output_dir: content/finance/stocks