source "http://rubygems.org"

gem "activesupport"
gem "activemodel"
gem "alphavantagerb"
gem "daru", git: "https://github.com/SciRuby/daru.git"
gem "global"
gem "rake"
gem 'retriable'
gem "zeitwerk"

group :development, :test do
  gem "pry-byebug"
end

group :test do
  gem "rspec"
end
